[package]
name = "explain_struct"
version = "0.1.0"
edition = "2021"
author = "Rafael Martín"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
